name: "LEVIR Lab"
description: "This is the official webpage for the LEVIR Lab directed by Prof. Zhenwei Shi at Beihang University."

#url: "https://kyanchen.github.io/levir"
#baseurl: "https://kyanchen.github.io/levir"

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/

collections:
        affiliates:
                output: true
        members:
                output: true
        publications:
                output: true
        news:
                output: true
        reviews:
                output: true
        alumni:
                output: true
        tags:
                output: true
        album:
                output: true